[env:az-delivery-devkit-v4]
platform = espressif32
board = az-delivery-devkit-v4
framework = espidf
monitor_speed = 115200
lib_extra_dirs =
  ../../common/esp-idf-lib/components
  ../../common
build_flags =
  -DCONFIG_I2CDEV_TIMEOUT=100000
